-- Remove the retired starter merchandise requested on 2026-10-04.
-- Match the reviewed IDs AND names AND brands; intended products reusing
-- an ID are never deleted. Historical orders store their own item snapshots.
-- This forward migration also prevents historical seeds returning on db reset.
begin;
set local lock_timeout = '5s';
delete from public.products as product
using (values
  (1, 'Prada Single-Breasted Wool & Silk Suit', 'Prada'),
  (2, 'Prada Super 150s Wool Tuxedo Suit', 'Prada'),
  (3, 'Prada Fine Cashmere Crew-Neck Sweater', 'Prada'),
  (4, 'Prada Wool & Silk V-Neck Sweater', 'Prada'),
  (5, 'Prada Re-Nylon Technical Bermuda Shorts', 'Prada'),
  (6, 'Prada Single-Breasted Tailored Flannel Blazer', 'Prada'),
  (7, 'Prada Poplin Short-Sleeve Bowling Shirt', 'Prada'),
  (8, 'Prada Tailored Wool Flannel Shirt', 'Prada'),
  (9, 'Prada Straight-Leg Flannel Trousers', 'Prada'),
  (10, 'Prada Nappa Leather Biker Jacket', 'Prada'),
  (11, 'Prada Brushed Cashmere Crewneck Sweater', 'Prada'),
  (12, 'Prada Bleached Organic Denim Jacket', 'Prada'),
  (13, 'Prada Re-Nylon Hooded Puffer Coat', 'Prada'),
  (14, 'Prada Hawaiian Print Silk Shirt', 'Prada'),
  (15, 'Prada Double Cashmere Dinner Suit', 'Prada'),
  (16, 'Prada Fine Stretch Oxford Shirt', 'Prada'),
  (17, 'Prada Lightweight Re-Nylon Vest', 'Prada'),
  (18, 'Prada Vintage Check Short-Sleeve Shirt', 'Prada'),
  (19, 'Prada Bowling Short Sleeve Silk Shirt', 'Prada'),
  (20, 'Prada Slim Fit Cotton Trousers', 'Prada'),
  (21, 'Prada Technical Re-Nylon Anorak', 'Prada'),
  (22, 'Prada Heavy Wool Knit Turtleneck', 'Prada'),
  (23, 'Prada Distressed Leather Car Coat', 'Prada'),
  (24, 'Prada Ribbed Wool Zip-Up Sweater', 'Prada'),
  (25, 'Gibson London Navy Texture Tailored Suit', 'Gibson London'),
  (26, 'Marc Darcy Charcoal Windowpane Check Suit', 'Marc Darcy'),
  (27, 'Racing Green Light Blue Linen Blend Suit', 'Racing Green'),
  (28, 'Limehaus Slim Fit Olive Green Suit', 'Limehaus'),
  (29, 'Gibson London Navy Textured Suit Trousers', 'Gibson London'),
  (30, 'Prada Embroidered Poplin Midi Shirt Dress', 'Prada'),
  (31, 'Prada Re-Nylon & Silk Satin Evening Gown', 'Prada'),
  (32, 'Prada Single-Breasted Velvet Tailored Jacket', 'Prada'),
  (33, 'Prada Double Wool Gabardine Trench Coat', 'Prada'),
  (34, 'Prada Oversized Nappa Leather Biker Jacket', 'Prada'),
  (35, 'Prada Silk Twill Printed Bow Top', 'Prada'),
  (36, 'Prada Fine Cashmere Knit Cardigan', 'Prada'),
  (37, 'Prada Angora Blend Cropped Sweater', 'Prada'),
  (38, 'Prada Organza Sheer Layered Shirt', 'Prada'),
  (39, 'Prada Heavy Silk Satin Wrap Top', 'Prada'),
  (40, 'Prada Printed Poplin Short-Sleeve Blouse', 'Prada'),
  (41, 'Prada Bull Denim Oversized Jacket', 'Prada'),
  (42, 'Prada Re-Nylon Padded Down Jacket', 'Prada'),
  (43, 'Prada High-Waisted Wide-Leg Wool Trousers', 'Prada'),
  (44, 'Prada Re-Nylon Circular Pleated Midi Skirt', 'Prada'),
  (45, 'Prada Vintage Denim Straight Jeans', 'Prada'),
  (46, 'Prada Re-Nylon Technical Active Leggings', 'Prada'),
  (47, 'Prada Linea Rossa Tech Crop Top', 'Prada'),
  (48, 'Prada Linea Rossa Windbreaker Zip Jacket', 'Prada'),
  (49, 'Rolex Oyster Perpetual Steel & Gold Watch', 'Rolex'),
  (50, 'Cartier Tank Rose Gold Leather Watch', 'Cartier'),
  (51, 'TAG Heuer Carrera Automatic Chronograph', 'TAG Heuer'),
  (52, '18K Solid Yellow Gold Cuban Link Chain', 'ALKEBULAN Fine Jewelry'),
  (53, 'Diamond Solitaire Gold Pendant Necklace', 'ALKEBULAN Fine Jewelry'),
  (54, 'Freshwater Cultured Pearl Strand Necklace', 'ALKEBULAN Fine Jewelry'),
  (55, '18K Gold Chunky Huggie Hoop Earrings', 'ALKEBULAN Fine Jewelry'),
  (56, 'Brilliant Cut Diamond Stud Earrings', 'ALKEBULAN Fine Jewelry'),
  (57, 'Gucci GG Marmont Matelassé Shoulder Bag', 'Gucci'),
  (58, 'Lacoste All-Over Print Messenger Bag', 'Lacoste'),
  (59, 'Nike Air Max 95 Sport Backpack', 'Nike'),
  (60, 'MONTIREX Ridge 32L Outdoor Backpack', 'Montirex'),
  (61, 'Limehaus Navy Leather Gibson Shoes', 'Limehaus'),
  (62, 'Ted Baker Charcoal Slim Fit Suit Trousers', 'Ted Baker'),
  (63, 'Marc Darcy Olive Wool Blend Suit Trousers', 'Marc Darcy'),
  (64, 'Racing Green Light Blue Linen Suit Trousers', 'Racing Green'),
  (65, 'Prada Printed Silk Organza Midi Dress', 'Prada'),
  (66, 'Prada Heavy Satin Backless Column Dress', 'Prada'),
  (67, 'Prada Re-Nylon Utility Belted Shirt Dress', 'Prada'),
  (68, 'Prada Draped Georgette Cocktail Dress', 'Prada'),
  (69, 'Racing Green Tan Leather Brogue Shoes', 'Racing Green'),
  (70, 'Clarks Tan Leather Oxford Suit Shoes', 'Clarks'),
  (71, 'Anatomic Co Brown Leather Penny Loafers', 'Anatomic Co'),
  (72, 'Clarks Black Leather Formal Derby Shoes', 'Clarks'),
  (73, 'Adidas Ultraboost 1.0 Performance Running Shoes', 'Adidas'),
  (74, 'Adidas Tiro 23 League Training Tracksuit Pants', 'Adidas'),
  (75, 'Adidas Originals Trefoil Essentials Fleece Hoodie', 'Adidas'),
  (76, 'Adidas Samba OG Leather Classic Sneakers', 'Adidas'),
  (77, 'Adidas Essentials 3-Stripes Windbreaker Jacket', 'Adidas'),
  (78, 'Adidas Originals Gazelle Bold Platform Sneakers', 'Adidas'),
  (79, 'Adidas Techfit High-Waisted Training Leggings', 'Adidas'),
  (80, 'Adidas Powerimpact Medium-Support Sports Bra', 'Adidas'),
  (81, 'Adidas Originals Oversized Trefoil Sweatshirt', 'Adidas'),
  (82, 'Adidas Always Original Pleated Track Skirt', 'Adidas'),
  (83, 'Ted Baker Olive Tweed Wool Blend Blazer', 'Ted Baker'),
  (84, 'Ted Baker Light Blue Check Tailored Blazer', 'Ted Baker'),
  (85, 'Ted Baker Tan Hopsack Wool Suit Blazer', 'Ted Baker'),
  (86, 'Marc Darcy Navy Slim Fit Tuxedo Blazer', 'Marc Darcy'),
  (87, 'Gibson London Charcoal Textured Wool Blazer', 'Gibson London'),
  (88, 'Nike  air max 90 infrared gore-tex sneakers', 'Nike')
) as legacy(id, name, brand)
where product.id = legacy.id
  and product.name = legacy.name
  and product.brand = legacy.brand;
commit;
